name: Deploy Backend  # Name of the workflow

on:
  # Runs the workflow on any push to the main branch, including the initial deployment
  push:
    branches:
      - main  

  # Runs the workflow when a pull request is successfully merged into the main branch
  pull_request:
    branches:
      - main  
    types:
      - closed  

jobs:
  deploy:
    # Ensures the workflow runs for both push to main and PR merge into main
    if: github.event_name == 'push' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')

    runs-on: ubuntu-latest  # Specifies the job to run on an Ubuntu-based runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Clones the repository into the runner for processing

      - name: Deploy to EC2 (SCP)
        uses: appleboy/scp-action@v0.1.3  # Uses SCP to securely copy backend files to EC2 instance
        with:
          host: ${{ secrets.EC2_HOST }}  
          username: ${{ secrets.EC2_USER }}  
          key: ${{ secrets.EC2_KEY }}  
          source: "."  # Copies everything from the repo root
          target: "/var/www/abegarage2025.com/backend/"  # The target directory on EC2

      - name: Copy .env file from backup folder
        run: |
          # Copy the .env file from the backup to the backend directory
          cp /var/www/abegarage2025.com/backend_backup/.env /var/www/abegarage2025.com/backend/

      - name: Restart Backend (SSH)
        uses: appleboy/ssh-action@master  # Uses SSH to run commands on the EC2 instance
        with:
          host: ${{ secrets.EC2_HOST }}  
          username: ${{ secrets.EC2_USER }}  
          key: ${{ secrets.EC2_KEY }}  
          script: |
            # Navigate to the backend directory
            cd /var/www/abegarage2025.com/backend/
            npm install  # Ensure all dependencies are installed
            pm2 restart backend || pm2 start app.js --name backend  # Restart if running, else start backend
